### ISSUE TITLE
use detection code of sonarqube directly

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/sonarqube-repair#75]
i.e. get the "offline" mode working, without the Web API (that was the initial idea actually)

(per our discussion on today's meeting)

**Comment by henry-lp** [comment]
I looked around a bit. There are 2 ways I can think of. 
* Install server locally either by docker or their bin file by downloading the `.zip` for installation . This solution would make the tool more inconvenience.
  * to run their server locally with the bin file, it requires Java 11
  * Docker is great but will have problem in the Jenkins plugin later
* Use `JavaCheckVerifier` during runtime. I investigated this a bit today and found some issues. This fires some warnings regarding this is illegal and will be fixed in the future (I check the maintainer of this class on Git and they seems to be inactive regarding this- google `net.sf.cglib.core.ReflectUtisl`).  

Currently I am working on the second solution and it requires some workaround like running JUnit in the normal code to bypass the `java.lang.AssertionError` by `CheckVerifier` inside `JavaCheckVerifier` when it found issues with the file. I can't catch the exception through JavaCheckVerifier, which require workaround. Any great tips of how to do this would be great :) .

**Comment by henry-lp** [comment]
Will make a PR for this after PR #80 and #81 are merged :) .

**Comment by henry-lp** [comment]
Per discussion, Fernanda is working on this issue :) .
